---
- name: Install requirements as given in specified file
  hosts: localhost
  gather_facts: true
  become: true

  tasks:
    - include_tasks: 10-get-requirements-file.yml
    - include_tasks: 20-apt-installs.yml
    - include_tasks: 30-install-miniconda.yml
    - include_tasks: 40-miniconda-and-pip-installs.yml

